/**:
  ros__parameters:
    use_sim_time: true
    use_imu_as_input: false
    prop_at_freq_of_imu: true
    check_satu: true
    init_map_size: 10
    point_filter_num: 1
    space_down_sample: true
    filter_size_surf: 0.5
    filter_size_map: 0.5
    ivox_nearby_type: 6
    runtime_pos_log_enable: false
    runtime_log_path: /tmp/point_lio_sim_log

    common:
      lid_topic: /livox/lidar
      imu_topic: /sim/imu
      con_frame: false
      con_frame_num: 1
      cut_frame: false
      cut_frame_time_interval: 0.1
      print_cloud_input_fps: false
      cloud_input_fps_print_period: 1.0
      debug_pose_update_detail: false
      debug_pose_update_detail_period: 1.0
      time_diff_lidar_to_imu: 0.0

    prior_pcd:
      enable: false
      prior_pcd_map_path: ""
      init_pose: [0.0, 0.0, 0.0]

    preprocess:
      lidar_type: 1
      scan_line: 4
      timestamp_unit: 3
      blind: 0.35
      blind_center_enable: true
      blind_center: [0.0, 0.2, 0.0]

    mapping:
      imu_en: true
      extrinsic_est_en: false
      imu_time_inte: 0.005
      lidar_time_inte: 0.1
      satu_acc: 29.43
      satu_gyro: 35.0
      acc_norm: 9.81
      lidar_meas_cov: 0.01
      acc_cov_output: 500.0
      gyr_cov_output: 1000.0
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      imu_meas_acc_cov: 0.01
      imu_meas_omg_cov: 0.01
      gyr_cov_input: 0.01
      acc_cov_input: 0.1
      plane_thr: 0.1
      pose_update_time_bin_ms: 2.0
      match_s: 81.0
      ivox_grid_resolution: 2.0
      gravity: [0.0, 0.0, -9.81]
      gravity_init: [0.0, 0.0, -9.81]
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]

    odometry:
      publish_odometry_without_downsample: true
      publish_frequency_hz: 100

    publish:
      path_en: true
      scan_publish_en: true
      scan_bodyframe_pub_en: false
      tf_send_en: true

    pcd_save:
      pcd_save_en: false
      accumulated_map_publish_hz: 1.0
      interval: 3600
